package com.talent.mapper;

import com.talent.entity.money;
import com.talent.entity.moneyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface moneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int countByExample(moneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int deleteByExample(moneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int insert(money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int insertSelective(money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    List<money> selectByExample(moneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    money selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") money record, @Param("example") moneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") money record, @Param("example") moneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(money record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(money record);
}