package com.talent.entity;

public class money {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Bid
     *
     * @mbggenerated
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Mtime
     *
     * @mbggenerated
     */
    private String mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Mmoney
     *
     * @mbggenerated
     */
    private String mmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.Mother
     *
     * @mbggenerated
     */
    private String mother;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Mid
     *
     * @return the value of money.Mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Mid
     *
     * @param mid the value for money.Mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Tid
     *
     * @return the value of money.Tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Tid
     *
     * @param tid the value for money.Tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Bid
     *
     * @return the value of money.Bid
     *
     * @mbggenerated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Bid
     *
     * @param bid the value for money.Bid
     *
     * @mbggenerated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Mtime
     *
     * @return the value of money.Mtime
     *
     * @mbggenerated
     */
    public String getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Mtime
     *
     * @param mtime the value for money.Mtime
     *
     * @mbggenerated
     */
    public void setMtime(String mtime) {
        this.mtime = mtime == null ? null : mtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Mmoney
     *
     * @return the value of money.Mmoney
     *
     * @mbggenerated
     */
    public String getMmoney() {
        return mmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Mmoney
     *
     * @param mmoney the value for money.Mmoney
     *
     * @mbggenerated
     */
    public void setMmoney(String mmoney) {
        this.mmoney = mmoney == null ? null : mmoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.Mother
     *
     * @return the value of money.Mother
     *
     * @mbggenerated
     */
    public String getMother() {
        return mother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.Mother
     *
     * @param mother the value for money.Mother
     *
     * @mbggenerated
     */
    public void setMother(String mother) {
        this.mother = mother == null ? null : mother.trim();
    }
}