package com.talent.entity;

public class tcontract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcontract.TCid
     *
     * @mbggenerated
     */
    private Integer tcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcontract.TCname
     *
     * @mbggenerated
     */
    private String tcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcontract.TCcontent
     *
     * @mbggenerated
     */
    private String tccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcontract.Tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcontract.TCother
     *
     * @mbggenerated
     */
    private String tcother;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcontract.TCid
     *
     * @return the value of tcontract.TCid
     *
     * @mbggenerated
     */
    public Integer getTcid() {
        return tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcontract.TCid
     *
     * @param tcid the value for tcontract.TCid
     *
     * @mbggenerated
     */
    public void setTcid(Integer tcid) {
        this.tcid = tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcontract.TCname
     *
     * @return the value of tcontract.TCname
     *
     * @mbggenerated
     */
    public String getTcname() {
        return tcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcontract.TCname
     *
     * @param tcname the value for tcontract.TCname
     *
     * @mbggenerated
     */
    public void setTcname(String tcname) {
        this.tcname = tcname == null ? null : tcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcontract.TCcontent
     *
     * @return the value of tcontract.TCcontent
     *
     * @mbggenerated
     */
    public String getTccontent() {
        return tccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcontract.TCcontent
     *
     * @param tccontent the value for tcontract.TCcontent
     *
     * @mbggenerated
     */
    public void setTccontent(String tccontent) {
        this.tccontent = tccontent == null ? null : tccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcontract.Tid
     *
     * @return the value of tcontract.Tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcontract.Tid
     *
     * @param tid the value for tcontract.Tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcontract.TCother
     *
     * @return the value of tcontract.TCother
     *
     * @mbggenerated
     */
    public String getTcother() {
        return tcother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcontract.TCother
     *
     * @param tcother the value for tcontract.TCother
     *
     * @mbggenerated
     */
    public void setTcother(String tcother) {
        this.tcother = tcother == null ? null : tcother.trim();
    }
}