server:
  port: 8080

spring:
  datasource:
    name: teacher
    url: jdbc:mysql://127.0.0.1:3308/rcpq?serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.talent.entity  # 注意：对应实体类的路径